name: Daily Fixture Fetch

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-fixtures:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check environment variables
      run: |
        if [ -z "$SUPABASE_URL" ]; then
          echo "Error: SUPABASE_URL is not set"
          exit 1
        fi
        if [ -z "$SUPABASE_KEY" ]; then
          echo "Error: SUPABASE_KEY is not set"
          exit 1
        fi
        if [ -z "$RAPIDAPI_KEY" ]; then
          echo "Error: RAPIDAPI_KEY is not set"
          exit 1
        fi
        echo "All required environment variables are set"
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        
    - name: Run fixture fetcher
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: python fixtures_fetcher.py 
